---
- name: Collectio IOS Facts
  hosts: all
  vars:
  - results: results
  
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - ios_facts: provider={{ios_provider}}
  - snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: cisco


  - template:
      src: template/report_template.j2
      dest: report/report.txt
    vars:
      allhosts: "{{hostvars}}"


  - copy: content="{{hostvars[inventory_hostname]|to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.json
