---
- name: Collectio IOS Facts
  hosts: all
  vars:
   - report: report
  
  tasks:
  - file: path={{report}} state=directory
    run_once: true
  - ios_facts: provider={{ios_provider}}
  - snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: cisco


  - template:
      src: template/report_template.j2
      dest: "{{report}}/report.md"
    vars:
      allhosts: "{{hostvars}}"
    run_once: true


